version: "3"
services:

   db:
     image: jaychiu/mysql:5.5
     volumes:
       - /data/mysql/mydata2:/var/lib/mysql
     ports:
       - "3307:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: jaychiu2017
       MYSQL_DATABASE: wordpress
       MYSQL_USER: admin
       MYSQL_PASSWORD: jaychiu2017

   wordpress:
     depends_on:
       - db
     image: jaychiu/wordpress:4.9.1
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: admin
       WORDPRESS_DB_PASSWORD: jaychiu2017
