db:
  container_name: my-db-container
  image: jaychiu/mysql:5.5
  ports:
    - "3306:3306"
  volumes:
    - /data/mysql/mydata:/var/lib/mysql

web:
  container_name: my-web-container
  image: hello:2.0
  ports:
    - "80:8080"
  environment:
    - DB_HOST=192.168.10.152
