#
# MAINTAINER        jaychiu <18698577365@163.com>
# DOCKER-VERSION    17.09.1-ce
#
# Dockerizing Jenkins: Dockerfile for building Jenkins images
#
FROM       jaychiu/jdk:1.7.0
MAINTAINER jaychiu <18698577365@163.com>

# Add docker command
USER root
RUN  curl -O https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz && \
     tar zxvf docker-latest.tgz && \
     cp docker/docker /usr/local/bin/ && \
     rm -rf docker docker-latest.tgz
ARG  DOCKER_GID=993

ENV JENKINS_HOME /var/jenkins_home
ENV JENKINS_VERSION 1.609.1
ENV JENKINS_UC https://updates.jenkins-ci.org
ENV COPY_REFERENCE_FILE_LOG /var/log/copy_reference_file.log

RUN useradd -d "$JENKINS_HOME" -u 1000 -m -s /bin/bash jenkins && \
    mkdir -p /usr/share/jenkins/ref/init.groovy.d

COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
COPY jenkins.war /usr/share/jenkins/jenkins.war

# RUN curl -fL http://mirrors.jenkins-ci.org/war-stable/$JENKINS_VERSION/jenkins.war -o /usr/share/jenkins/jenkins.war && \

RUN chown -R jenkins "$JENKINS_HOME" /usr/share/jenkins/ref && \
    touch $COPY_REFERENCE_FILE_LOG && chown jenkins.jenkins $COPY_REFERENCE_FILE_LOG

# 将 `jenkins` 用户的组 ID 改为宿主 `docker` 组的组ID，从而具有执行 `docker` 命令的权限。
USER jenkins:${DOCKER_GID}

VOLUME /var/jenkins_home

EXPOSE 8080 50000

COPY jenkins.sh /usr/local/bin/jenkins.sh

ENTRYPOINT ["/usr/local/bin/jenkins.sh"]
