version: "2"
services:
  zookeeper:
    container_name: iop-zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: iop-kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: iop-zookeeper:2181
      KAFKA_CREATE_TOPICS: "metrics"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_BROKER_ID: 1
    ports:
      - "9092:9092"
    links:
      - zookeeper

